#!/bin/bash

mkdir -p tmp/distributions

{
  if [ "$1" ] && [ "$2" ]; then
    echo $1 $2
  else
    echo "alpine /bin/bash /usr/bin/dash /bin/busybox"
    echo "debian /bin/bash /bin/dash /bin/busybox"
  fi
} | while read os shells; do
  image=ta_$os
  outfile=tmp/distributions/$image.buildlog

  echo "make $image..."
  if docker build -t $image test/dockerfiles/$os >$outfile 2>&1; then
    echo "success"
  else
    echo "fail"
    exit 1
  fi

  for shell in $shells; do
    outfile=tmp/distributions/${image}_$(basename $shell)
    echo "test $image $shell..."
    {
      docker run -i --rm -v $PWD:/tmp/ta -w /tmp/ta $image /bin/bash 2>&1 <<EOF
ln -sf $shell /bin/sh
test/suite
EOF
    } | tee $outfile
    echo
  done
done
