#!/bin/bash

mkdir -p tmp/distributions
while read os shells; do
  image="ts_$os"
  outfile=tmp/distributions/"$image".buildlog

  printf "make %s ... " "$image"
  if docker build -t "$image" dockerfiles/"$os" >"$outfile" 2>&1
  then
    echo "success"
  else
    echo "fail"
    exit 1
  fi

  for shell in $shells; do
    outfile=tmp/distributions/"$image"_"$(basename "$shell")"

    echo "test $image $shell..."
    docker run -i --rm -v $PWD:/tmp/ts -w /tmp/ts "$image" $shell >"$outfile" 2>&1 <<EOF
if [ "$shell" != /bin/sh ]
  then ln -sf "$shell" /bin/sh
fi
test/suite
EOF
    #tail -n 1 "$outfile"
    cat $outfile
    echo
  done
done <<EOF
alpine /bin/bash /bin/zsh
centos /bin/bash /bin/zsh /bin/ksh
debian /bin/bash /bin/zsh /bin/ksh
fedora /bin/bash /bin/zsh /bin/ksh
opensuse /bin/bash /bin/zsh /bin/ksh
ubuntu /bin/dash /bin/bash /bin/zsh /bin/ksh
EOF
