#!/bin/bash

mkdir -p tmp/distributions
while read os shells; do
  image=ts_$os
  outfile=tmp/distributions/$image.buildlog

  echo "make $image..."
  if docker build -t $image test/dockerfiles/$os >$outfile 2>&1; then
    echo "success"
  else
    echo "fail"
    exit 1
  fi

  for shell in $shells; do
    outfile=tmp/distributions/${image}_$(basename $shell)
    echo "test $image $shell..."
    {
      docker run -i --rm -v $PWD:/tmp/tea -w /tmp/tea $image /bin/bash 2>&1 <<EOF
ln -sf $shell /bin/sh
test/suite
EOF
    } | tee $outfile
    echo
  done
done <<EOF
alpine /bin/bash /usr/bin/dash /bin/busybox
debian /bin/bash /bin/dash /bin/busybox
EOF
