#!/usr/bin/env sh
TESTDIR=$(cd "$(dirname $0)" && pwd)
BASEDIR=$TESTDIR/..

PATH=$PATH:$BASEDIR/bin

prog_ok () {
  echo "prog ok"
}

prog_fail () {
  echo "prog fail"
  return 2
}

prog_trap () {
  echo "prog trap"
  false
  return 0
}

prog_param () {
  echo "prog $1"
}

test_call_ok () {
  t_call prog_ok
  t_expect_eq $t_CALL_RET 0
  t_expect_eq '$t_CALL_OUT' "prog ok"
}

test_call_failing () {
  t_call prog_fail
  t_expect_eq $t_CALL_RET 2
  t_expect_eq '$t_CALL_OUT' "prog fail"
}

test_call_trapped () {
  t_call prog_trap
  t_expect_eq $t_CALL_RET 1
  t_expect_eq '$t_CALL_OUT' "prog trap"
}

test_call_param () {
  t_call prog_param "message"
  t_expect_eq $t_CALL_RET 0
  t_expect_eq '$t_CALL_OUT' "prog message"
}

test_call_not_found () {
  t_call prog_missing 2>/dev/null
  t_expect_eq $t_CALL_RET 127
}

test_call_cleans_state () {
  t_expect_eq $t_CALL_RET ""
  t_expect_eq '$t_CALL_OUT' ""
}

. test-again
