#!/usr/bin/env sh
TESTDIR=$(cd "$(dirname $0)" && pwd)
BASEDIR=$TESTDIR/..

PATH=$PATH:$BASEDIR/bin
CASES=$TESTDIR/cases

call_test () {
  _t_SUB_INDENT=""
  t_call -perr $CASES/skip $t_TEST_NAME
  t_expect_eq '$t_CALL_RET' 0
  t_expect_eq '$t_CALL_OUT' "$1"
}

test_skip () {
  call_test "\
1..1
ok 1 test_skip # skip"
}

test_skip_reason () {
  call_test "\
1..1
ok 1 test_skip_reason # skip Skipping..."
}

. test-again
