#!/usr/bin/env sh
TESTDIR=$(cd "$(dirname $0)" && pwd)
BASEDIR=$TESTDIR/..

PATH=$PATH:$BASEDIR/bin
CASES=$TESTDIR/cases

call_test () {
  _t_SUB_INDENT=""
  t_call -perr $CASES/fail $t_TEST_NAME
  t_expect_eq '$t_CALL_RET' 1
  t_expect_eq '$t_CALL_OUT' "$1"
}

test_fail_exit () {
  call_test "\
1..1
not ok 1 $t_TEST_NAME"
}

test_fail_return () {
  call_test "\
1..1
not ok 1 $t_TEST_NAME"
}

test_fail_trap () {
  call_test "\
1..1
not ok 1 $t_TEST_NAME"
}

test_fail_expect_ret_true () {
  call_test "\
1..1
# expect_ret failed
#   true
#  actual   0
#  expected 1
not ok 1 $t_TEST_NAME"
}

test_fail_expect_ret_false () {
  call_test "\
1..1
# expect_ret failed
#   false
#  actual   1
#  expected 0
not ok 1 $t_TEST_NAME"
}

test_fail_expect_out () {
  call_test \
'1..1
# expect_out failed
#   echo "hello world"
#  actual
#   hello world
#  expected
#   hell0 world
not ok 1 '$t_TEST_NAME
}

test_fail_expect_out_multiline () {
  call_test \
'1..1
# expect_out failed
#   for i in hello world; do echo $i; done
#  actual
#   hello
#   world
#  expected
#   hell0
#   world
not ok 1 '$t_TEST_NAME
}

test_fail_expect_eq () {
  call_test "\
1..1
# expect_eq failed
#   1
#  expected
#   2
not ok 1 $t_TEST_NAME"
}

test_fail_expect_eq_char () {
  call_test \
'1..1
# expect_eq failed
#   $a
#  actual
#   x
#  expected
#   X
not ok 1 '$t_TEST_NAME
}

test_fail_expect_eq_number () {
  call_test \
'1..1
# expect_eq failed
#   $a
#  actual
#   0
#  expected
#   1
not ok 1 '$t_TEST_NAME
}

test_multiple_expects_fail_early () {
  call_test "\
1..1
# expect_ret failed
#   true
#  actual   0
#  expected 1
not ok 1 $t_TEST_NAME"
}

test_multiple_expects_fail_late () {
  call_test "\
1..1
# expect_ret failed
#   true
#  actual   0
#  expected 1
not ok 1 $t_TEST_NAME"
}

. test-again
