#!/bin/sh

test_a () {
  echo "a"
  echo "A" >&2
  true
}

test_b () {
  echo "b"
  echo "B" >&2
  true
}

test_c () {
  echo "c"
  echo "C" >&2
  false
}

test_s () {
  skip "s"
  false
}

. test/helper
. ts
