#!/usr/bin/env sh

test_bdd () {
  t_given "a strig"
  local a="high"
  t_and "a number"
  local b=5
  t_when "calling printf"
  local c=$(printf "%s%d" $a $b)
  t_then "the result is the concatinated string"
  t_expect_eq '$c' "high5"
}

. test-again
