#!/usr/bin/env sh

test_change_working_dir () {
  mkdir "$t_TEST_TMP/dir"
  cd "$t_TEST_TMP/dir"
  t_expect_eq '$t_TEST_TMP/dir' "$(pwd)"
}

test_check_working_dir () {
  t_expect_eq '$t_BASE_DIR' "$(pwd)"
}

. test-again
