#!/usr/bin/env sh

test_change_working_dir () {
  cd "$t_BASE_DIR/bin"
  t_expect_value '$t_BASE_DIR/bin' "$(pwd)"
}

test_check_working_dir () {
  t_expect_value '$t_BASE_DIR' "$(pwd)"
}

. test/helper
. tea.sh
