#!/bin/sh

setup () {
  echo "in setup"
}

teardown () {
  echo "in teardown"
}

test_exit_fail_in_test_after_untrap () {
  echo "in test"
  trap - EXIT
  exit 1
}
#-> not ok test_exit_fail_in_test_after_untrap

. test/helper
. ts
