#!/usr/bin/env sh

t_setup_once () {
  >&2 echo "in setup once"
}

t_setup () {
  >&2 echo "in setup"
}

t_teardown_once () {
  >&2 echo "in teardown once"
  false
  exit 0
}

t_teardown () {
  >&2 echo "in teardown"
}

test_fail_in_teardown_once () {
  >&2 echo "in test"
}

. test-again
