#!/bin/sh

test_exit_pass () {
  exit
}
#) 1..10
#) ok 1 test_exit_pass

test_return_pass () {
  true
}
#) ok 2 test_return_pass

test_expect_status_true_pass () {
  t_expect_status true 0
}
#) ok 3 test_expect_status_true_pass

test_expect_status_false_pass () {
  t_expect_status false 1
}
#) ok 4 test_expect_status_false_pass

test_expect_output_pass () {
  t_expect_output 'echo "hello world"' "hello world"
}
#) ok 5 test_expect_output_pass

test_expect_output_multiline_pass () {
  t_expect_output 'for i in hello world; do echo $i; done' "\
hello
world"
}
#) ok 6 test_expect_output_multiline_pass

test_expect_value_pass () {
  t_expect_value 1 1
}
#) ok 7 test_expect_value_pass

test_expect_value_char_pass () {
  local a="x"
  t_expect_value '$a' x
}
#) ok 8 test_expect_value_char_pass

test_expect_value_number_pass () {
  local a=0
  t_expect_value '$a' 0
}
#) ok 9 test_expect_value_number_pass

test_multiple_expects_pass () {
  t_expect_status true 0
  t_expect_output "echo 0" "0"
  t_expect_value  0 0
}
#) ok 10 test_multiple_expects_pass

. test/helper
. tea.sh
