#!/bin/sh

export PATH="$PWD/test/examples/public_function_conflict.d:$PATH"

test_setup_and_teardown_commands_on_PATH_are_ignored () {
  echo "in test"
}
#-> 1..1
#-> ok 1 test_setup_and_teardown_commands_on_PATH_are_ignored

. test/helper
. ts
