#!/bin/sh

t_setup () {
  echo "in setup"
  false
}

t_teardown () {
  echo "in teardown"
}

test_return_fail_in_setup () {
  echo "in test"
}
#-> 1..1
#-> not ok 1 test_return_fail_in_setup

. test/helper
. tea.sh
