#!/usr/bin/env sh
TESTDIR=$(cd "$(dirname $0)" && pwd)

test_subtest_pass () {
  t_subtest "$TESTDIR/ok"
}

test_subtest_fail () {
  t_subtest $TESTDIR/abc
}

test_subtest_pass_fail () {
  t_subtest $TESTDIR/abc
}

test_subsubtest () {
  t_subtest $TESTDIR/subsubtest
}

. test-again
