#!/bin/sh

test_common () {
  true
}
#-> ok test_common

test_with_whitespace 	 () {
  true
}
#-> ok test_with_whitespace

test_without_whitespace() {
  true
}
#-> ok test_without_whitespace

  test_leading_whitespace () {
  true
}
#-> ok test_leading_whitespace

test_oneline () { true; }
#-> ok test_oneline

test_subshell () (
  true
)
#-> ok test_subshell

test_subshell_oneline () ( true )
#-> ok test_subshell_oneline

. test/helper
. ts
