#!/usr/bin/env sh

test_common () {
  true
}

test_with_whitespace 	 () {
  true
}

test_without_whitespace() {
  true
}

  test_leading_whitespace () {
  true
}

test_oneline () { true; }

test_subshell () (
  true
)

test_subshell_oneline () ( true )

. test/helper
. test-again
