#!/bin/sh

test_common () {
  true
}
#) 1..7
#) ok 1 test_common

test_with_whitespace 	 () {
  true
}
#) ok 2 test_with_whitespace

test_without_whitespace() {
  true
}
#) ok 3 test_without_whitespace

  test_leading_whitespace () {
  true
}
#) ok 4 test_leading_whitespace

test_oneline () { true; }
#) ok 5 test_oneline

test_subshell () (
  true
)
#) ok 6 test_subshell

test_subshell_oneline () ( true )
#) ok 7 test_subshell_oneline

. test/helper
. tea.sh
