#!/usr/bin/env sh

t_setup () {
  echo "in setup"
  false
  return 0
}

t_teardown () {
  echo "in teardown"
}

test_trap_fail_in_setup () {
  echo "in test"
}
#) 1..1
#) not ok 1 test_trap_fail_in_setup

. test/helper
. tea.sh
