#!/usr/bin/env sh

t_setup () {
  echo "in setup"
}

t_teardown () {
  echo "in teardown"
}

test_trap_fail_in_test () {
  echo "in test"
  false
  return 0
}
#) 1..1
#) not ok 1 test_trap_fail_in_test

. test/helper
. tea.sh
