#!/bin/sh

test_ts_fails_for_use_of_undeclared_variable () {
  unset var
  t_expect_value '$var' ""
}
#-> 1..2
#-> not ok 1 test_ts_fails_for_use_of_undeclared_variable

test_ts_can_use_undeclared_variables_with_set_u () {
  set +u
  unset var
  t_expect_value '$var' ""
}
#-> ok 2 test_ts_can_use_undeclared_variables_with_set_u

. test/helper
. tea.sh
