#!/bin/sh

test_ts_fails_for_use_of_undeclared_variable () {
  unset var
  expect_value '$var' ""
}
#-> not ok test_ts_fails_for_use_of_undeclared_variable

test_ts_can_use_undeclared_variables_with_set_u () {
  set +u
  unset var
  expect_value '$var' ""
}
#-> ok test_ts_can_use_undeclared_variables_with_set_u

. test/helper
. ts
