#!/bin/bash
CMDPATH=$(cd "$(dirname $0)" && pwd)
BASEDIR=$CMDPATH/../..

TMP=$BASEDIR/tmp/$(basename $0)
mkdir -p $TMP

{
  if [ "$1" ] && [ "$2" ]; then
    echo $1 $2
  else
    echo "alpine /bin/bash /usr/bin/dash /bin/busybox"
    echo "debian /bin/bash /bin/dash /bin/busybox"
  fi
} | while read os shells; do
  image=ta_$os
  outfile=$TMP/$image.buildlog

  echo "make $image..."
  cd $CMDPATH/$os
  if docker build -t $image . >$outfile 2>&1; then
    echo "ok"
  else
    echo "failed"
    exit 1
  fi

  for shell in $shells; do
    outfile=$TMP/${image}_$(basename $shell)
    echo "test $image $shell..."
    {
      docker run -i --rm -v $BASEDIR:/ta -w /ta $image /bin/bash 2>&1 <<EOF
ln -sf $shell /bin/sh
./test/suite
EOF
    } | tee $outfile
    echo
  done
done
